### ISSUE TITLE
Plugin adds color hexcodes to the tags of a post

### ISSUE THREAD

**Issue by alizehctl** [florian-rieder/gutenbergp5#1]
Hi! Thanks for making this elegant plugin.

I just tried it out and noticed [my post](https://aadils.computer/1209-2/) got tagged with a bunch of random color hexcodes? I didn't add them myself, so I can only assume they were added by the plugin. 

![image](https://github.com/florian-rieder/gutenbergp5/assets/31581044/73f0659a-9adb-4771-88d1-53155f4daf99)

It's a nifty feature, but is there a way to disable it?

**Comment by alizehctl** [comment]
Whoops, I think I made a mistake. These were added by the other p5.js block plugin I tried out before using your plugin. Never mind!

**Comment by alizehctl** [comment]
Hmm but they keep reappearing, even though I disabled the other plugin, and they only get added to [this post](https://aadils.computer/1209-2/). Maybe it is being triggered by this plugin after all?

I've removed them for now, hopefully they won't show up again.

EDIT: yup, it's definitely being caused by this plugin, i'm seeing color tags on [all the p5 posts](https://aadils.computer/tag/p5-js/)

**Comment by alizehctl** [comment]
I can now confirm that the tags are being added by the "Code Block Pro" plugin, since they showed up on a [post which had no p5js embed in it](https://aadils.computer/1260-2/). Sorry for the issue spam!

**Comment by florian-rieder** [comment]
Glad this plugin isn't the cause of your troubles, and wish you the best in troubleshooting your issue !
Thank you for your interest in the plugin !
