### ISSUE TITLE
Getting the page's URL

### ISSUE THREAD

**Issue by Ultomato** [florian-rieder/gutenbergp5#3]
Hi Florian,
Thanks for sharing your webpages and for your help with the p5 plugin for Wordpress the other week.

I've put my p5 code into a module, then saved to Divi, saved it in my divi module library. It works in a demo, but I'm hoping to drop the module into many pages, and have the code get the URL, parse it, then use that information for a page-specific graphic. I've been able to write javescript that can get the URL and parse it in a Divi code module, but this code doesn't seem to work within your Easy p5 plugin.

Do you know of a way to have this functionality within your plugin?

The code is this:
  let currentUrl = window.location.href; 

  //print ("URL: "+ currentUrl);  
  if (currentUrl.includes("north")) {
    region = "North Yukon";
    let urlArray = currentUrl.split("-");
    let urlEnd = urlArray[2];
    // document.writeln(urlEnd); 
    // document.write("</br>"); 
    lmu =  urlEnd.slice(0,-1);
  } else if (currentUrl.includes("peel")) {
    region = "Peel Watershed";
    let urlArray = currentUrl.split("-");
    let urlEnd = urlArray[2];
    // document.writeln(urlEnd); 
    // document.write("</br>"); 
    lmu =  urlEnd.slice(0,-1);  

  } else if (currentUrl.includes("dawson")) {
    region = "Dawson";
    let urlArray = currentUrl.split("/");
    let urlEnd = urlArray[3];
    // document.writeln(urlEnd); 
    // document.write("</br>"); 
    lmu =  urlEnd.slice(3);  

  } else {
    region = "No data";
    lmu = -1;
  }

Thanks again!
Sam

**Comment by florian-rieder** [comment]
Hi Sam,

This issue stems from the fact that iframes are used to contain the sketches. As such, `window.location.href` will output `about:srcdoc` instead of the URL of the page. To fix this, you need to select the parent window using `window.parent.location.href` instead.

This should fix your issue.

Cheers,
Florian
